---
apiVersion: v1
kind: Service
metadata:
  name: apcupsd-svc
  namespace: apcupsd
  labels:
    app.kubernetes.io/name: apcupsd
spec:
  type: ClusterIP
  ports:
    - port: 3551
      targetPort: apcupsd
      protocol: TCP
      name: apcupsd
  selector:
    app.kubernetes.io/name: apcupsd
